services:
  database:
    image: mariadb:10.11
    container_name: habit_tracker_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: habit_tracker
      MYSQL_USER: habit_user
      MYSQL_PASSWORD: habitTracker123!
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo:7
    container_name: habit_tracker_mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: habit_tracker_backend
    restart: always
    volumes:
      - ../habit-tracker-api:/var/www/backend
    depends_on:
      - database
      - mongodb

  nginx:
    image: nginx:alpine
    container_name: habit_tracker_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../habit-tracker-api:/var/www/backend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  frontend:
    image: node:20-alpine
    container_name: habit_tracker_frontend
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - ../habit-tracker:/app
    ports:
      - "5173:5173"
    depends_on:
      - nginx

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: habit_tracker_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    depends_on:
      - database

  mongo-express:
    image: mongo-express
    container_name: habit_tracker_mongo_express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb

volumes:
  database_data:
  mongodb_data: